"""Core public contracts for the VASP analyzer."""

from .config import FrozenModel
from .errors import (
    AnalyzerError,
    DatasetConsistencyError,
    IncompleteIonicStep,
    IncompleteTail,
    MalformedBlock,
    OutcarFormatError,
    PoscarFormatError,
    ProfileValidationError,
    StructureMismatchError,
    UnknownMethodError,
    UnsupportedDialect,
    VolumetricAlignmentError,
)
from .models import (
    CalculationDataset,
    Capability,
    EnergyTerm,
    ForceComponent,
    InitialStructure,
    IonicStep,
    Mat3,
    ParameterOccurrence,
    ParserProvenance,
    ParserWarning,
    SelectiveMask,
    Site,
    SourceFile,
    Vec3,
    VolumetricDescriptor,
    VolumetricRequest,
)

__all__ = [
    "AnalyzerError",
    "CalculationDataset",
    "Capability",
    "DatasetConsistencyError",
    "EnergyTerm",
    "ForceComponent",
    "FrozenModel",
    "IncompleteIonicStep",
    "IncompleteTail",
    "InitialStructure",
    "IonicStep",
    "MalformedBlock",
    "Mat3",
    "OutcarFormatError",
    "ParameterOccurrence",
    "ParserProvenance",
    "ParserWarning",
    "PoscarFormatError",
    "ProfileValidationError",
    "SelectiveMask",
    "Site",
    "SourceFile",
    "StructureMismatchError",
    "UnknownMethodError",
    "UnsupportedDialect",
    "Vec3",
    "VolumetricAlignmentError",
    "VolumetricDescriptor",
    "VolumetricRequest",
]
